language: rust
sudo: required
dist: trusty
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - nightly
script:
- cargo clean
- cargo build 
- cargo test --features=all -- --nocapture
