language: rust
sudo: required
dist: trusty
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - beta
  - nightly 
script:
  - cargo clean
  - cargo build 
  - cargo test -- --nocapture
