[package]
name = "underscore"
version = "0.1.0"
authors = ["rowlandsonpratt <striderman34@gmail.com>"]

[dependencies]
underscore_syntax =  {path="../underscore_syntax"}
underscore_util =  {path="../underscore_util"}